// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double higherThanHalf = 0;
		double halfAndLower = 0;
		double ratio = 0;
		for (int i = 0; i < n; i++) {
			double x = Math.random();
			if (x <= 0.5) {
				halfAndLower++;
				
			} else {
				higherThanHalf++;
			}
		}
		//if ( halfAndLower > higherThanHalf) {
		//	ratio = halfAndLower / higherThanHalf;
		//} else {
		//	ratio = higherThanHalf / halfAndLower;
		//}
		ratio = higherThanHalf / halfAndLower;
		System.out.println("> 0.5:   " + (int) higherThanHalf + " times");
		System.out.println("<= 0.5:  " + (int) halfAndLower + " times");
		System.out.println("Ratio:   " + ratio);

	}
}
